title: Kessie Theliar Charles CV
logo: /assets/img/Kessie TC_Headsho_Photo_credit_Schaël Marceus.jpg
description: Research-based Artist
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
